### ISSUE TITLE
upload stream has error

### ISSUE THREAD

**Issue by mbfakourii** [Flutterando/uno#19]
Hello, I had a problem uploading the stream

```dart
Stream<List<int>>? data=...;


final uno.Response response = await _client.post(path,
    data:
        await data?.fold<List<int>>(<int>[], (List<int> previous, List<int> element) => previous..addAll(element)),
    headers: _getHeader(options),
    responseType: ResponseType.stream,
    onDownloadProgress: onSendProgress);
```
error
```
Status 400
```

**Comment by tauamendonca** [comment]
The code 400 refers to a Bad Request. Check if your 'post' method is sending your data correctly as your API demands.
If it's right, then please reopen the issue and give more details of what is expected. 

Also, there's a double dot in your method addAll
```dart
 previous..addAll(element)),
```
