### ISSUE TITLE
Move models to external or infra layer.

### ISSUE THREAD

**Issue by EdsonMello-code** [Flutterando/uno#2]
Hello man, model is in domain layer, it can be moved to infra or externals layer.

**Comment by jacobaraujo7** [comment]
Hi!
Why couldn't the model stay in the domain layer?

**Comment by EdsonMello-code** [comment]
In the domain, it needs to have business logic in the case of entities, but the model does two things, it serves as business logic and it also has conversion methods.

**Comment by jacobaraujo7** [comment]
How do you suggest?

**Comment by EdsonMello-code** [comment]
I could create an entity Request and create a mapper or model in externals that extends from Request, but I don't know if this falls into DRY.

**Comment by jacobaraujo7** [comment]
But Request aren't an entity. Because the business logic is Response. Request like is a DTO.

**Comment by EdsonMello-code** [comment]
Okay, I hadn't seen it this way. Thanks for replying.
