### ISSUE TITLE
Binary data

### ISSUE THREAD

**Issue by guplem** [Flutterando/uno#21]
Is there any way we can send binary data? (like a profile picture)
If so, can you provide an example?

I am trying to figure how to send an XFile (image) to an API endpoint.

**Comment by jacobaraujo7** [comment]
Use the FormData and send in Post.data property. 
This is a Multipart.

**Comment by guplem** [comment]
> Use the FormData and send in Post.data property. This is a Multipart.

Will try it out, please don't close this issue yet since I am 100% planning on working on this, but I can't check it just now.

**Comment by jacobaraujo7** [comment]
Use this:
```dart
final file = File('path/file.ext');
await uno.post('url', data: file.readAsBytesSync();
```
