### ISSUE TITLE
FormData fromMap in UNO

### ISSUE THREAD

**Issue by brunobmorais** [Flutterando/uno#22]
How to migrate this information format from DIO to UNO

<img width="366" alt="6FC245B8-F092-4F94-800C-4C9A52FA014E" src="https://user-images.githubusercontent.com/11892712/219510428-f73f0f10-67d2-41d1-a0cb-6608d9a5589f.png">

**Comment by jacobaraujo7** [comment]
Check the documentation:
![image](https://user-images.githubusercontent.com/4047813/219512455-d1ad1435-cf43-4ca5-a81a-83f28118a441.png)

**Comment by brunobmorais** [comment]
I followed the documentation as described, but I was unable to transcribe the following method to UNO.

O ERRO: 'UnoError: Data body isn`t a json. Please, use other [ResponseType] in request.

**Comment by jacobaraujo7** [comment]
> I followed the documentation as described, but I was unable to transcribe the following method to UNO.
> 
> O ERRO: 'UnoError: Data body isn`t a json. Please, use other [ResponseType] in request.

This error is related to the return of data.
The return, by default is a json, if you prefer a different type of json (coming from your backend) then you must change the ResponseType

**Comment by jacobaraujo7** [comment]
Check v1.1.1

**Comment by brunobmorais** [comment]
Thanks @ jacobaraujo7, but when I tried to use UNO it showed `Scheme not starting with alphabetic character` &https://url.com is showing Ampersand before https. I'm analyzing what could have happened.

**Comment by brunobmorais** [comment]
Thanks @ jacobaraujo7, but when I tried to use UNO it showed `Scheme not starting with alphabetic character` &https://url.com is showing Ampersand before https. I'm analyzing what could have happened.

**Comment by brunobmorais** [comment]
Thanks @ jacobaraujo7, but when I tried to use UNO it showed `Scheme not starting with alphabetic character` &https://url.com is showing Ampersand before https. I'm analyzing what could have happened.

**Comment by brunobmorais** [comment]
Thanks @ jacobaraujo7, but when I tried to use UNO it showed `Scheme not starting with alphabetic character` &https://url.com is showing Ampersand before https. I'm analyzing what could have happened.

**Comment by joaojsrbr** [comment]
> Thanks @ jacobaraujo7, but when I tried to use UNO it showed `Scheme not starting with alphabetic character` &https://url.com is showing Ampersand before https. I'm analyzing what could have happened.

![image](https://user-images.githubusercontent.com/42517034/219801808-0fc1e4e6-9848-48dd-8ebb-28ec24252eaa.png)
![image](https://user-images.githubusercontent.com/42517034/219801929-a41b6bcc-98ff-4f1f-9452-27d227c9931e.png)

**Comment by jacobaraujo7** [comment]
Thanks @joaojsrbr and @brunobmorais 
Fixed.
Version 1.1.2 published

**Comment by OrlandoEduardo101** [comment]
As said in the comment above, resolved in version 1.1.2, so I will close this issue.
