### ISSUE TITLE
It's missing "?" when build url with query parameters

### ISSUE THREAD

**Issue by jttuboi** [Flutterando/uno#29]
When you call `uno.get("/app/v1/payments", params: {"page": "1"});`, the url is built is `/app/v1/paymentspage=1`. It's missing "?".

<img width="567" alt="image" src="https://user-images.githubusercontent.com/376856/222236961-143c3e36-9a67-4b3c-bbe6-15d495e64a9b.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/376856/222237131-59e247ba-6f01-4590-8b0f-75553c11b200.png">

Fix like this:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/376856/222237962-576fbf27-df94-444a-9777-c5676a3d1c1f.png">

**Comment by jacobaraujo7** [comment]
Fixed.
v1.1.4
