### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by pedroenrre** [Flutterando/uno#3]
How can i make a refresh token with UNO?

**Comment by jacobaraujo7** [comment]
https://github.com/f-teamdev/ship/blob/dev/dashboard/lib/app/shared/services/network/uno/uno_network_interceptors.dart

**Comment by uberlei** [comment]
Alguém pode enviar um exemplo? esse link não esta mais funcionando.

**Comment by BlackLeg15** [comment]
@uberlei 
https://github.com/f-teamdev/ship/blob/main/dashboard/lib/app/app_module.dart
https://github.com/f-teamdev/ship/blob/main/dashboard/lib/app/core/services/network/uno/uno_network_interceptors.dart
