### ISSUE TITLE
Uno DataForm data in  post method

### ISSUE THREAD

**Issue by Dima2111** [Flutterando/uno#4]
UnoError (UnoError: Data body isn`t a json. Please, use other [ResponseType] in request.

How to solve this?

**Comment by Dima2111** [comment]
I want to send data in application/x-www-form-urlencoded

**Comment by Bwolfs2** [comment]
You will not send this on Body this is used on the header

**Comment by jacobaraujo7** [comment]
fixed v1.0.1
